# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_text', models.CharField(max_length=200)),
                ('favorite', models.CharField(max_length=200)),
                ('line', models.IntegerField(default=0)),
                ('network', models.CharField(max_length=200)),
                ('game_time', models.DateTimeField(verbose_name='game time/date')),
                ('game_of_week', models.BooleanField(default=False)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_text', models.CharField(max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Game')),
            ],
        ),
    ]
