# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0002_auto_20171031_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game_points',
            field=models.IntegerField(default=0),
        ),
    ]
