# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0003_team_game_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='team_1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='team_2',
            field=models.CharField(default='', max_length=200),
        ),
    ]
