# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0004_auto_20171031_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='game',
        ),
        migrations.RemoveField(
            model_name='game',
            name='pub_date',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
