# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0005_auto_20171031_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 16, 4, 8, 276097, tzinfo=utc), verbose_name='published'),
        ),
    ]
