# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 22:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0007_auto_20171031_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 22, 14, 6, 398483, tzinfo=utc), verbose_name='published'),
        ),
    ]
