# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0008_auto_20171031_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 22, 15, 47, 183868, tzinfo=utc), verbose_name='published'),
        ),
    ]
