# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-06 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0009_auto_20171031_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 6, 14, 10, 42, 330136, tzinfo=utc), verbose_name='published'),
        ),
    ]
