# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0012_auto_20171106_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='betting_sheet',
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 2, 17, 57, 35415, tzinfo=utc), verbose_name='published'),
        ),
    ]
