# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0013_auto_20171106_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=0, verbose_name='Week Number'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 2, 22, 2, 787469, tzinfo=utc), verbose_name='published'),
        ),
    ]
