# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 02:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0014_auto_20171106_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_text',
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 2, 24, 59, 667734, tzinfo=utc), verbose_name='published'),
        ),
    ]
