# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 02:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0015_auto_20171106_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_text',
            field=models.CharField(default='game', max_length=200, verbose_name='Game Index'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 2, 28, 47, 616292, tzinfo=utc), verbose_name='published'),
        ),
    ]
