# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 05:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0016_auto_20171106_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_num', models.IntegerField(default=0, verbose_name='Week Number')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 5, 2, 10, 734189, tzinfo=utc), verbose_name='published'),
        ),
    ]
