# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 05:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0017_auto_20171106_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeknum',
            name='date_start',
            field=models.DateField(default=datetime.datetime(2017, 11, 7, 5, 6, 49, 508028, tzinfo=utc), verbose_name='Week Starting'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 5, 6, 49, 507025, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 5, 6, 49, 507025, tzinfo=utc), verbose_name='published'),
        ),
    ]
