# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 05:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0019_auto_20171106_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeknum',
            old_name='date_start',
            new_name='start_date',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 5, 14, 22, 367198, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 5, 14, 22, 367198, tzinfo=utc), verbose_name='published'),
        ),
    ]
