# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 05:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0021_auto_20171106_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeknum',
            name='is_current_week',
            field=models.BooleanField(default=False, verbose_name='Current Week?'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 5, 29, 58, 3047, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 5, 29, 58, 3047, tzinfo=utc), verbose_name='published'),
        ),
    ]
