# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0024_auto_20171107_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_week_score',
            field=models.IntegerField(default=0, verbose_name="Last Week's Points"),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 21, 55, 12, 380500, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 21, 55, 12, 380500, tzinfo=utc), verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='weeknum',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 11, 9), verbose_name='Week Starting'),
        ),
    ]
