# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 22:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0025_auto_20171109_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='isActive',
            new_name='is_paid',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 22, 20, 2, 19489, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 22, 20, 2, 19489, tzinfo=utc), verbose_name='published'),
        ),
    ]
