# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 22:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0026_auto_20171109_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 22, 26, 17, 729611, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 22, 26, 17, 729611, tzinfo=utc), verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=0, verbose_name='Week in Season'),
        ),
    ]
