# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 23:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0027_auto_20171109_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='team_1',
            new_name='away_team',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='team_2',
            new_name='home_team',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 23, 18, 14, 719898, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 23, 18, 14, 719898, tzinfo=utc), verbose_name='published'),
        ),
    ]
