# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 07:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0030_auto_20171111_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bettingsheet',
            name='player',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 7, 27, 2, 778850, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 7, 27, 2, 778850, tzinfo=utc), verbose_name='published'),
        ),
        migrations.DeleteModel(
            name='BettingSheet',
        ),
    ]
