# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 07:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0031_auto_20171111_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPick',
            fields=[
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='betting.Player')),
                ('game_id', models.IntegerField(default=0, verbose_name='Game_ID')),
                ('team', models.CharField(default='', max_length=200, verbose_name='Team Name')),
                ('is_high_risk', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 7, 49, 25, 83265, tzinfo=utc), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='game',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 11, 7, 49, 25, 83265, tzinfo=utc), verbose_name='published'),
        ),
    ]
