# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0032_auto_20171111_0149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='savedpick',
            name='id',
            field=models.AutoField(auto_created=True, serialize=False, primary_key=True, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 18, 0), verbose_name='game time/date'),
        ),
        migrations.AlterField(
            model_name='savedpick',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Player'),
        ),
        migrations.AlterField(
            model_name='weeknum',
            name='start_date',
            field=models.DateField(default=datetime.date(2017, 1, 1), verbose_name='Week Starting'),
        ),
    ]
