# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-11 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0033_auto_20171111_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpick',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
