# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-12 03:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0036_auto_20171111_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpick',
            name='game_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Game_ID'),
        ),
    ]
