# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0038_auto_20171111_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_Of_Week_Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0, verbose_name='Game of Week Score')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.Player')),
            ],
        ),
    ]
