# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-16 21:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0039_game_of_week_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game_Of_Week_Score',
            new_name='GameOfWeekScore',
        ),
    ]
