# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0040_auto_20171116_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='PossibleGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(max_length=200)),
                ('away', models.CharField(max_length=200)),
                ('line', models.FloatField(default=0)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
