# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-18 05:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0044_possiblegame_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='possiblegame',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 1, 18, 0), verbose_name='game time/date'),
        ),
    ]
