# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0045_auto_20171117_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
