# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0047_savedpick_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedpick',
            name='id',
        ),
        migrations.AlterField(
            model_name='savedpick',
            name='game_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, verbose_name='Game_ID'),
        ),
    ]
