# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0049_auto_20171201_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpick',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedpick',
            name='game_id',
            field=models.IntegerField(default=0, verbose_name='Game_ID'),
        ),
    ]
