# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0050_auto_20171201_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpick',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
