# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betting', '0051_auto_20171201_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedpick',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
